image: eclipse-temurin:11-jdk-focal

variables:
  ANDROID_COMPILE_SDK: "30"
  ANDROID_BUILD_TOOLS: "30.0.3"
  ANDROID_SDK_TOOLS:   "9477386"

before_script:
  - apt-get --quiet update --yes
  - apt-get --quiet install --yes wget tar unzip lib32stdc++6 lib32z1 android-tools-adb
  - wget --quiet --output-document=android-sdk.zip https://dl.google.com/android/repository/commandlinetools-linux-${ANDROID_SDK_TOOLS}_latest.zip
  - unzip -d android-sdk-tmp android-sdk.zip
  - mkdir -p android-sdk-linux/cmdline-tools
  - mv android-sdk-tmp/cmdline-tools android-sdk-linux/cmdline-tools/latest
  - export ANDROID_SDK_ROOT=$PWD/android-sdk-linux
  - export PATH="$PATH:$ANDROID_SDK_ROOT/emulator:$ANDROID_SDK_ROOT/cmdline-tools/latest/bin"
  - echo y | sdkmanager "platforms;android-${ANDROID_COMPILE_SDK}" "emulator" >/dev/null
  - echo y | sdkmanager "platform-tools" >/dev/null
  - echo y | sdkmanager "build-tools;${ANDROID_BUILD_TOOLS}" >/dev/null

  # temporarily disable checking for EPIPE error and use yes to accept all licenses
  - set +o pipefail
  - yes | sdkmanager --sdk_root="$ANDROID_SDK_ROOT" --licenses
  - set -o pipefail

  # Create virtual device
  - sdkmanager --sdk_root="$ANDROID_SDK_ROOT" --install "system-images;android-${ANDROID_COMPILE_SDK};google_apis;x86_64"
  - sdkmanager --sdk_root="$ANDROID_SDK_ROOT" --list

  - echo no | avdmanager create avd --force --name TestAVD --package "system-images;android-${ANDROID_COMPILE_SDK};google_apis;x86_64" --tag "google_apis" --abi "x86_64" --device "pixel_5"

  - chmod +x ./gradlew

stages:
  - test
  - build
  - test

assemble:
  stage: build
  script:
    - ./gradlew clean assemble
  artifacts:
    paths:
    - app/build/outputs/

tests:
  stage: test
  script:
    - ./gradlew clean test

# Runner needs hardware acceleration enabled: x86_64 emulation currently requires hardware acceleration
# instrumented_tests:
#   stage: test
#   script:
#     # Start virtual device
#     - emulator -list-avds
#     - emulator -avd TestAVD -no-snapshot-save -no-audio -no-window -debug -verbose &
#     - adb wait-for-device devices
#     # Virtual device is ready
#     - adb devices
#     - ./gradlew connectedAndroidTest
